import type { editor } from "monaco-editor";

export interface VSCodeTheme {
  id: string;
  label: string;
  type: "dark" | "light";
  monaco: editor.IStandaloneThemeData;
  chrome: {
    bg: string;
    sidebar: string;
    activity: string;
    border: string;
    accent: string;
    text: string;
    textDim: string;
    tabBg: string;
    tabActive: string;
    statusBg: string;
  };
  colors: string[];
}

const xChrome = {
  bg: "#050505",
  sidebar: "#0a0a0a",
  activity: "#0d0d0d",
  border: "rgba(255,255,255,0.06)",
  accent: "#fc618d",
  text: "#e0e0e0",
  textDim: "#666",
  tabBg: "#0a0a0a",
  tabActive: "#1a1a1a",
  statusBg: "#0a0a0a",
};

const miamiChrome = {
  bg: "#000000",
  sidebar: "#0a0008",
  activity: "#0d000a",
  border: "rgba(255,76,139,0.12)",
  accent: "#FF4C8B",
  text: "#f0e6ee",
  textDim: "#886677",
  tabBg: "#0a0008",
  tabActive: "#1a0011",
  statusBg: "#0d000a",
};

const osloChrome = {
  bg: "#181a1f",
  sidebar: "#1d1f23",
  activity: "#202228",
  border: "rgba(255,255,255,0.06)",
  accent: "#76cce0",
  text: "#abb2bf",
  textDim: "#7f8490",
  tabBg: "#1d1f23",
  tabActive: "#2c313c",
  statusBg: "#181a1f",
};

const tokioChrome = {
  bg: "#191919",
  sidebar: "#1e1e1e",
  activity: "#222222",
  border: "rgba(255,255,255,0.06)",
  accent: "#fc618d",
  text: "#e0e0e0",
  textDim: "#666",
  tabBg: "#1e1e1e",
  tabActive: "#2a2a2a",
  statusBg: "#1e1e1e",
};

const berlinChrome = {
  bg: "#000000",
  sidebar: "#070707",
  activity: "#0a0a0a",
  border: "rgba(255,255,255,0.04)",
  accent: "#888",
  text: "#cccccc",
  textDim: "#555",
  tabBg: "#070707",
  tabActive: "#111111",
  statusBg: "#070707",
};

const prahaChrome = {
  bg: "#1a1a1a",
  sidebar: "#1e1e1e",
  activity: "#202020",
  border: "rgba(255,255,255,0.06)",
  accent: "#BD93F9",
  text: "#e0e0e0",
  textDim: "#666",
  tabBg: "#1e1e1e",
  tabActive: "#2a2a2a",
  statusBg: "#1e1e1e",
};

export const themes: Record<string, VSCodeTheme> = {
  x: {
    id: "x",
    label: "X",
    type: "dark",
    chrome: xChrome,
    colors: ["#fc618d", "#fce566", "#7bd88f", "#fd9353", "#948ae3", "#5ad4e6"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "fc618d" },
        { token: "string", foreground: "fce566" },
        { token: "string.css", foreground: "fce566" },
        { token: "number", foreground: "fd9353" },
        { token: "type", foreground: "948ae3" },
        { token: "function", foreground: "7bd88f" },
        { token: "comment", foreground: "555555", fontStyle: "italic" },
        { token: "variable", foreground: "e0e0e0" },
        { token: "variable.predefined", foreground: "fc618d" },
        { token: "tag", foreground: "fc618d" },
        { token: "attribute.name", foreground: "fce566" },
        { token: "attribute.value", foreground: "7bd88f" },
        { token: "delimiter", foreground: "666666" },
        { token: "identifier", foreground: "e0e0e0" },
        { token: "string.key.json", foreground: "fce566" },
        { token: "string.value.json", foreground: "7bd88f" },
        { token: "delimiter.json", foreground: "666666" },
        { token: "property", foreground: "fce566" },
      ],
      colors: {
        "editor.background": "#050505",
        "editor.foreground": "#e0e0e0",
        "editorLineNumber.foreground": "#555555",
        "editorCursor.foreground": "#fc618d",
        "editor.selectionBackground": "#bab6c026",
        "editor.lineHighlightBackground": "#f7f1ff0c",
        "editorIndentGuide.background": "#333333",
        "editorIndentGuide.activeBackground": "#555555",
      },
    },
  },
  miami: {
    id: "miami",
    label: "Miami",
    type: "dark",
    chrome: miamiChrome,
    colors: ["#FF4C8B", "#FFD84C", "#7FFFD4", "#00FFA8", "#D36CFF", "#47CFFF"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "FF4C8B" },
        { token: "string", foreground: "FFD84C" },
        { token: "string.css", foreground: "FFD84C" },
        { token: "number", foreground: "00FFA8" },
        { token: "type", foreground: "D36CFF" },
        { token: "function", foreground: "7FFFD4" },
        { token: "comment", foreground: "666666", fontStyle: "italic" },
        { token: "variable", foreground: "f0e6ee" },
        { token: "variable.predefined", foreground: "FF4C8B" },
        { token: "tag", foreground: "FF4C8B" },
        { token: "attribute.name", foreground: "FFD84C" },
        { token: "attribute.value", foreground: "7FFFD4" },
        { token: "delimiter", foreground: "886677" },
        { token: "identifier", foreground: "f0e6ee" },
        { token: "string.key.json", foreground: "FFD84C" },
        { token: "string.value.json", foreground: "7FFFD4" },
        { token: "property", foreground: "FFD84C" },
      ],
      colors: {
        "editor.background": "#000000",
        "editor.foreground": "#f0e6ee",
        "editorLineNumber.foreground": "#664455",
        "editorCursor.foreground": "#FF4C8B",
        "editor.selectionBackground": "#b0b0b026",
        "editor.lineHighlightBackground": "#f7f1ff0c",
        "editorIndentGuide.background": "#331122",
        "editorIndentGuide.activeBackground": "#664455",
      },
    },
  },
  oslo: {
    id: "oslo",
    label: "Oslo",
    type: "dark",
    chrome: osloChrome,
    colors: ["#76cce0", "#8cc265", "#9ed072", "#ff6600", "#c162de", "#e2e2e3"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "c162de" },
        { token: "string", foreground: "9ed072" },
        { token: "string.css", foreground: "9ed072" },
        { token: "number", foreground: "ff6600" },
        { token: "type", foreground: "76cce0" },
        { token: "function", foreground: "8cc265" },
        { token: "comment", foreground: "7f8490", fontStyle: "italic" },
        { token: "variable", foreground: "abb2bf" },
        { token: "tag", foreground: "c162de" },
        { token: "attribute.name", foreground: "ff6600" },
        { token: "attribute.value", foreground: "8cc265" },
        { token: "delimiter", foreground: "7f8490" },
        { token: "identifier", foreground: "abb2bf" },
        { token: "string.key.json", foreground: "9ed072" },
        { token: "string.value.json", foreground: "8cc265" },
        { token: "property", foreground: "9ed072" },
      ],
      colors: {
        "editor.background": "#181a1f",
        "editor.foreground": "#abb2bf",
        "editorLineNumber.foreground": "#7f8490",
        "editorCursor.foreground": "#528bff",
        "editor.selectionBackground": "#67769660",
        "editor.lineHighlightBackground": "#2c313c",
        "editorIndentGuide.background": "#3b4048",
        "editorIndentGuide.activeBackground": "#7f8490",
      },
    },
  },
  tokio: {
    id: "tokio",
    label: "Tokio",
    type: "dark",
    chrome: tokioChrome,
    colors: ["#fc618d", "#fce566", "#7bd88f", "#fd9353", "#948ae3", "#5ad4e6"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "fc618d" },
        { token: "string", foreground: "fce566" },
        { token: "string.css", foreground: "fce566" },
        { token: "number", foreground: "fd9353" },
        { token: "type", foreground: "948ae3" },
        { token: "function", foreground: "7bd88f" },
        { token: "comment", foreground: "555555", fontStyle: "italic" },
        { token: "variable", foreground: "e0e0e0" },
        { token: "tag", foreground: "fc618d" },
        { token: "attribute.name", foreground: "fce566" },
        { token: "attribute.value", foreground: "7bd88f" },
        { token: "delimiter", foreground: "666666" },
        { token: "identifier", foreground: "e0e0e0" },
        { token: "property", foreground: "fce566" },
      ],
      colors: {
        "editor.background": "#191919",
        "editor.foreground": "#e0e0e0",
        "editorLineNumber.foreground": "#555555",
        "editorCursor.foreground": "#fc618d",
        "editor.selectionBackground": "#bab6c026",
        "editor.lineHighlightBackground": "#f7f1ff0c",
        "editorIndentGuide.background": "#333333",
        "editorIndentGuide.activeBackground": "#555555",
      },
    },
  },
  berlin: {
    id: "berlin",
    label: "Berlin",
    type: "dark",
    chrome: berlinChrome,
    colors: ["#888", "#aaa", "#ccc", "#666", "#999", "#bbb"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "999999" },
        { token: "string", foreground: "cccccc" },
        { token: "string.css", foreground: "cccccc" },
        { token: "number", foreground: "aaaaaa" },
        { token: "type", foreground: "bbbbbb" },
        { token: "function", foreground: "dddddd" },
        { token: "comment", foreground: "444444", fontStyle: "italic" },
        { token: "variable", foreground: "cccccc" },
        { token: "tag", foreground: "999999" },
        { token: "attribute.name", foreground: "bbbbbb" },
        { token: "attribute.value", foreground: "dddddd" },
        { token: "delimiter", foreground: "444444" },
        { token: "identifier", foreground: "cccccc" },
        { token: "property", foreground: "bbbbbb" },
      ],
      colors: {
        "editor.background": "#000000",
        "editor.foreground": "#cccccc",
        "editorLineNumber.foreground": "#444444",
        "editorCursor.foreground": "#888888",
        "editor.selectionBackground": "#ffffff15",
        "editor.lineHighlightBackground": "#ffffff08",
        "editorIndentGuide.background": "#222222",
        "editorIndentGuide.activeBackground": "#444444",
      },
    },
  },
  praha: {
    id: "praha",
    label: "Praha",
    type: "dark",
    chrome: prahaChrome,
    colors: ["#BD93F9", "#FFE4A3", "#8cc265", "#ff6600", "#c162de", "#76cce0"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "BD93F9" },
        { token: "string", foreground: "FFE4A3" },
        { token: "string.css", foreground: "FFE4A3" },
        { token: "number", foreground: "ff6600" },
        { token: "type", foreground: "76cce0" },
        { token: "function", foreground: "8cc265" },
        { token: "comment", foreground: "666666", fontStyle: "italic" },
        { token: "variable", foreground: "e0e0e0" },
        { token: "tag", foreground: "BD93F9" },
        { token: "attribute.name", foreground: "FFE4A3" },
        { token: "attribute.value", foreground: "8cc265" },
        { token: "delimiter", foreground: "666666" },
        { token: "identifier", foreground: "e0e0e0" },
        { token: "property", foreground: "FFE4A3" },
      ],
      colors: {
        "editor.background": "#1a1a1a",
        "editor.foreground": "#e0e0e0",
        "editorLineNumber.foreground": "#555555",
        "editorCursor.foreground": "#BD93F9",
        "editor.selectionBackground": "#BD93F933",
        "editor.lineHighlightBackground": "#ffffff0c",
        "editorIndentGuide.background": "#333333",
        "editorIndentGuide.activeBackground": "#555555",
      },
    },
  },
  madrid: {
    id: "madrid",
    label: "Madrid",
    type: "light",
    chrome: {
      bg: "#fafafa",
      sidebar: "#f5f5f5",
      activity: "#f0f0f0",
      border: "rgba(0,0,0,0.08)",
      accent: "#990026",
      text: "#1a1a1a",
      textDim: "#666",
      tabBg: "#f5f5f5",
      tabActive: "#ffffff",
      statusBg: "#f0f0f0",
    },
    colors: ["#990026", "#007a28", "#8a6408", "#007a9e", "#4d2699", "#007a9e"],
    monaco: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "990026" },
        { token: "string", foreground: "8a6408" },
        { token: "string.css", foreground: "8a6408" },
        { token: "number", foreground: "007a9e" },
        { token: "type", foreground: "4d2699" },
        { token: "function", foreground: "007a28" },
        { token: "comment", foreground: "999999", fontStyle: "italic" },
        { token: "variable", foreground: "1a1a1a" },
        { token: "tag", foreground: "990026" },
        { token: "attribute.name", foreground: "8a6408" },
        { token: "attribute.value", foreground: "007a28" },
        { token: "delimiter", foreground: "cccccc" },
        { token: "identifier", foreground: "1a1a1a" },
        { token: "property", foreground: "8a6408" },
      ],
      colors: {
        "editor.background": "#fafafa",
        "editor.foreground": "#1a1a1a",
        "editorLineNumber.foreground": "#bbbbbb",
        "editorCursor.foreground": "#990026",
        "editor.selectionBackground": "#99002620",
        "editor.lineHighlightBackground": "#00000008",
        "editorIndentGuide.background": "#dddddd",
        "editorIndentGuide.activeBackground": "#bbbbbb",
      },
    },
  },
  london: {
    id: "london",
    label: "London",
    type: "light",
    chrome: {
      bg: "#ffffff",
      sidebar: "#f8f8f8",
      activity: "#f5f5f5",
      border: "rgba(0,0,0,0.06)",
      accent: "#555",
      text: "#2b2b2b",
      textDim: "#999",
      tabBg: "#f8f8f8",
      tabActive: "#ffffff",
      statusBg: "#f5f5f5",
    },
    colors: ["#333", "#444", "#555", "#666", "#777", "#888"],
    monaco: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "333333" },
        { token: "string", foreground: "555555" },
        { token: "string.css", foreground: "555555" },
        { token: "number", foreground: "666666" },
        { token: "type", foreground: "777777" },
        { token: "function", foreground: "444444" },
        { token: "comment", foreground: "bbbbbb", fontStyle: "italic" },
        { token: "variable", foreground: "2b2b2b" },
        { token: "tag", foreground: "333333" },
        { token: "attribute.name", foreground: "555555" },
        { token: "attribute.value", foreground: "444444" },
        { token: "delimiter", foreground: "dddddd" },
        { token: "identifier", foreground: "2b2b2b" },
        { token: "property", foreground: "555555" },
      ],
      colors: {
        "editor.background": "#ffffff",
        "editor.foreground": "#2b2b2b",
        "editorLineNumber.foreground": "#cccccc",
        "editorCursor.foreground": "#555555",
        "editor.selectionBackground": "#00000015",
        "editor.lineHighlightBackground": "#00000006",
        "editorIndentGuide.background": "#e8e8e8",
        "editorIndentGuide.activeBackground": "#cccccc",
      },
    },
  },
  helsinki: {
    id: "helsinki",
    label: "Helsinki",
    type: "light",
    chrome: {
      bg: "#f8fafe",
      sidebar: "#f0f4fa",
      activity: "#eef2f8",
      border: "rgba(0,0,0,0.06)",
      accent: "#1faa9e",
      text: "#2c2e34",
      textDim: "#8a8d95",
      tabBg: "#f0f4fa",
      tabActive: "#ffffff",
      statusBg: "#eef2f8",
    },
    colors: ["#1faa9e", "#733d9a", "#2e70ad", "#b55a0f", "#3e9d21", "#bd4c3d"],
    monaco: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "733d9a" },
        { token: "string", foreground: "2e70ad" },
        { token: "string.css", foreground: "2e70ad" },
        { token: "number", foreground: "b55a0f" },
        { token: "type", foreground: "1faa9e" },
        { token: "function", foreground: "3e9d21" },
        { token: "comment", foreground: "b0a999", fontStyle: "italic" },
        { token: "variable", foreground: "2c2e34" },
        { token: "tag", foreground: "733d9a" },
        { token: "attribute.name", foreground: "2e70ad" },
        { token: "attribute.value", foreground: "3e9d21" },
        { token: "delimiter", foreground: "ccccdd" },
        { token: "identifier", foreground: "2c2e34" },
        { token: "property", foreground: "2e70ad" },
      ],
      colors: {
        "editor.background": "#f8fafe",
        "editor.foreground": "#2c2e34",
        "editorLineNumber.foreground": "#b0b4bc",
        "editorCursor.foreground": "#1faa9e",
        "editor.selectionBackground": "#1faa9e20",
        "editor.lineHighlightBackground": "#00000006",
        "editorIndentGuide.background": "#dde0e6",
        "editorIndentGuide.activeBackground": "#b0b4bc",
      },
    },
  },
  lahabana: {
    id: "lahabana",
    label: "Lahabana",
    type: "dark",
    chrome: {
      bg: "#19191a",
      sidebar: "#1e1e1f",
      activity: "#222223",
      border: "rgba(255,255,255,0.06)",
      accent: "#e5ff9d",
      text: "#e0e0e0",
      textDim: "#666",
      tabBg: "#1e1e1f",
      tabActive: "#2a2a2b",
      statusBg: "#1e1e1f",
    },
    colors: ["#e5ff9d", "#fc618d", "#7bd88f", "#fd9353", "#948ae3", "#5ad4e6"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "fc618d" },
        { token: "string", foreground: "e5ff9d" },
        { token: "string.css", foreground: "e5ff9d" },
        { token: "number", foreground: "fd9353" },
        { token: "type", foreground: "948ae3" },
        { token: "function", foreground: "7bd88f" },
        { token: "comment", foreground: "555555", fontStyle: "italic" },
        { token: "variable", foreground: "e0e0e0" },
        { token: "tag", foreground: "fc618d" },
        { token: "attribute.name", foreground: "e5ff9d" },
        { token: "attribute.value", foreground: "7bd88f" },
        { token: "delimiter", foreground: "666666" },
        { token: "identifier", foreground: "e0e0e0" },
        { token: "property", foreground: "e5ff9d" },
      ],
      colors: {
        "editor.background": "#19191a",
        "editor.foreground": "#e0e0e0",
        "editorLineNumber.foreground": "#555555",
        "editorCursor.foreground": "#e5ff9d",
        "editor.selectionBackground": "#bab6c026",
        "editor.lineHighlightBackground": "#f7f1ff0c",
        "editorIndentGuide.background": "#333333",
        "editorIndentGuide.activeBackground": "#555555",
      },
    },
  },
  paris: {
    id: "paris",
    label: "Paris",
    type: "dark",
    chrome: {
      bg: "#1a0a30",
      sidebar: "#1f0e36",
      activity: "#23103d",
      border: "rgba(255,255,255,0.06)",
      accent: "#c4bdff",
      text: "#e0e0e0",
      textDim: "#8b888f",
      tabBg: "#1f0e36",
      tabActive: "#2a1548",
      statusBg: "#23103d",
    },
    colors: ["#c4bdff", "#fc618d", "#7bd88f", "#fce566", "#a3f3ff", "#948ae3"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "c4bdff" },
        { token: "string", foreground: "fce566" },
        { token: "string.css", foreground: "fce566" },
        { token: "number", foreground: "a3f3ff" },
        { token: "type", foreground: "948ae3" },
        { token: "function", foreground: "7bd88f" },
        { token: "comment", foreground: "665577", fontStyle: "italic" },
        { token: "variable", foreground: "e0e0e0" },
        { token: "tag", foreground: "c4bdff" },
        { token: "attribute.name", foreground: "fce566" },
        { token: "attribute.value", foreground: "7bd88f" },
        { token: "delimiter", foreground: "665577" },
        { token: "identifier", foreground: "e0e0e0" },
        { token: "property", foreground: "fce566" },
      ],
      colors: {
        "editor.background": "#1a0a30",
        "editor.foreground": "#e0e0e0",
        "editorLineNumber.foreground": "#554466",
        "editorCursor.foreground": "#c4bdff",
        "editor.selectionBackground": "#c4bdff26",
        "editor.lineHighlightBackground": "#ffffff0c",
        "editorIndentGuide.background": "#2a1548",
        "editorIndentGuide.activeBackground": "#554466",
      },
    },
  },
  bogota: {
    id: "bogota",
    label: "Bogota",
    type: "dark",
    chrome: {
      bg: "#200b0a",
      sidebar: "#26100f",
      activity: "#2a1312",
      border: "rgba(255,255,255,0.06)",
      accent: "#ffed89",
      text: "#e0e0e0",
      textDim: "#8b888f",
      tabBg: "#26100f",
      tabActive: "#331a18",
      statusBg: "#2a1312",
    },
    colors: ["#ffed89", "#fc618d", "#7bd88f", "#47e6ff", "#ff9999", "#948ae3"],
    monaco: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "fc618d" },
        { token: "string", foreground: "ffed89" },
        { token: "string.css", foreground: "ffed89" },
        { token: "number", foreground: "47e6ff" },
        { token: "type", foreground: "948ae3" },
        { token: "function", foreground: "7bd88f" },
        { token: "comment", foreground: "665544", fontStyle: "italic" },
        { token: "variable", foreground: "e0e0e0" },
        { token: "tag", foreground: "fc618d" },
        { token: "attribute.name", foreground: "ffed89" },
        { token: "attribute.value", foreground: "7bd88f" },
        { token: "delimiter", foreground: "665544" },
        { token: "identifier", foreground: "e0e0e0" },
        { token: "property", foreground: "ffed89" },
      ],
      colors: {
        "editor.background": "#200b0a",
        "editor.foreground": "#e0e0e0",
        "editorLineNumber.foreground": "#554433",
        "editorCursor.foreground": "#ffed89",
        "editor.selectionBackground": "#ffed8926",
        "editor.lineHighlightBackground": "#ffffff0c",
        "editorIndentGuide.background": "#331a18",
        "editorIndentGuide.activeBackground": "#554433",
      },
    },
  },
};

export const themeList = Object.values(themes);
export const defaultTheme = themes.x;
